//
// Created by hemin on 25-7-10.
//

#ifndef TOKENTYPE_H
#define TOKENTYPE_H
// define toke type
enum class TokenType
{
    SET,INT,IDENTIFIER,EQUAL,NUMBER,HEXADDRESS,
    PRINT,FIND,MOV,TO,PLUS,MINUS,MULTIPLY,DIVIDE,
    NEWLINE,END,AT,IF,EQUALITY,LEFT_PAREN,RIGHT_PAREN,
    LEFT_BRACE,RIGHT_BRACE,STRING,SELECTOR,BYTE,IN
};
#endif //TOKENTYPE_H
